version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: mysql
  rust:
    build:
      context: .
      dockerfile: ./docker/rust/Dockerfile
    environment:
      USER: root
    depends_on:
      - db
    command:
      [
        "wait-for-it",
        "db:3306",
        "-t",
        "5",
        "--",
        "/work/target/release/rust-mysql-redis-client-usage",
      ]
    container_name: rust
